
```{r}
library(tidyverse)
library(skimr)
library(lubridate)

my_theme <- theme_minimal() +
  theme(plot.title = element_text(size = 16, color  = 'dodgerblue4'),
        axis.text.x=element_text(size=10),
        axis.text.y=element_text(size=10),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14))


BB.df <- read.csv('charts_since2000.csv')
skim_without_charts(BB.df)
```

```{r}
BB.df <- BB.df %>% 
  select(date, song, artist, rank, weeks.on.board) %>% 
  mutate(date = ymd(date)) 

summary(BB.df)
```


```{r}
top_ten_all <- BB.df %>% 
  distinct(song, artist, .keep_all = TRUE) %>% 
  top_n(9, weeks.on.board) %>% 
  arrange(desc(weeks.on.board)) 

top_ten_all[6,3] <- 'LMFAO'

ggplot(data = top_ten_all, aes(x = fct_reorder(paste(artist, song, year(date), 
    sep = ' - '), weeks.on.board), y = weeks.on.board)) + 
  geom_bar(stat = 'identity', 
           color = 'black', 
           fill = '#fa8f95') + 
  geom_text(aes(label = weeks.on.board, y = weeks.on.board - 5)) + 
  coord_flip() + 
  labs(y = 'Weeks on Board', 
       x = 'Song',
       title = 'Billboard 2000-2022') +
  my_theme 
```

```{r}
top_artists <- BB.df %>% 
  distinct(song, .keep_all = TRUE) %>% 
  group_by(artist) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  rename(number_of_songs = n) %>% 
  filter(artist != 'Glee Cast') %>%
  top_n(10, number_of_songs)

ggplot(data = top_artists, aes(x = fct_reorder(artist, number_of_songs), 
                               y = number_of_songs)) + 
  geom_bar(stat = 'identity',
           color = 'black',
           fill = 'darkseagreen1') +
  geom_text(aes(label = number_of_songs, y =  number_of_songs - 5)) + 
  coord_flip() + 
  labs(y = 'Number of Songs on Board',
       x = 'Artist',
       title = 'Most Popular Artists 2000-2022') +
  my_theme
```

```{r}
library(wordcloud2) 
 
# Change the shape:
wordcloud2(demoFreq, size = 0.7, shape = 'star')
```


```{r}
demoFreq
```

<!-- ```{r} -->

<!-- number_of_songs_per_artist <- ggplot( -->
<!--   data = top_artist_all_year, -->
<!--   mapping = aes(rank, group = artist,  -->
<!--                 color = as.factor(artist), fill = as.factor(artist)) -->
<!--   ) + -->
<!--   geom_tile(mapping = aes(y = number_of_songs/2, height = number_of_songs), show.legend = FALSE, alpha = 0.7) +  -->
<!--   geom_text(aes(y = 0, label = paste(artist, " ")), vjust = 0.2, hjust = 1, size = 8)  + -->
<!--   coord_flip(clip = "off", expand = FALSE) + -->
<!--   scale_y_continuous(labels = scales::comma) + -->
<!--   scale_x_reverse() + -->
<!--   scale_color_viridis_d() +  -->
<!--   #scale_size(range = c(2, 12)) +  -->
<!--   labs(x = "number_of_songs", y = "artist") + -->
<!--   guides(color = "none", fill = "none") + -->
<!--   theme(axis.line=element_blank(), -->
<!--         axis.text.x=element_blank(), -->
<!--         axis.text.y=element_blank(), -->
<!--         axis.ticks=element_blank(), -->
<!--         axis.title.x=element_blank(), -->
<!--         axis.title.y=element_blank(), -->
<!--         legend.position="none", -->
<!--         panel.background=element_blank(), -->
<!--         panel.border=element_blank(), -->
<!--         panel.grid.major=element_blank(), -->
<!--         panel.grid.minor=element_blank(), -->
<!--         panel.grid.major.x = element_line( size=.1, color="grey" ), -->
<!--         panel.grid.minor.x = element_line( size=.1, color="grey" ), -->
<!--         plot.title=element_text(size=40, hjust=0.5, face="bold", colour="grey", vjust=-1), -->
<!--         plot.subtitle=element_text(size=25, hjust=0.5, face="italic", color="grey"), -->
<!--         plot.caption = element_text(size=25, hjust=0.5, vjust=1, face="italic", color="grey"), -->
<!--         plot.background=element_blank(), -->
<!--         plot.margin = margin(2,2, 2, 13, "cm")) #top, rigth, bottom, left -->



<!-- anim <- number_of_songs_per_artist + transition_states(year, transition_length = 4, state_length = 1) + -->
<!--   view_follow(fixed_x = TRUE) + -->
<!--   labs(title = 'Number of Songs on Billboards in year {closest_state}', -->
<!--        subtitle  =  "Top 10 Artist", -->
<!--        caption  = "Total Number of Songs") -->

<!-- animate(anim, 1000, fps = 20,  width = 1200, height = 1000, -->
<!--         renderer = gifski_renderer("artist_songs.gif")) -->


<!-- ``` -->


